# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newProject' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newProject

  

  platform :ios, '9.0'
  target 'newProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'newProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newProject-tvOS

  target 'newProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
